platform :ios, '9.0'

target 'assignment' do
  use_frameworks!

  pod 'Alamofire', '~> 4.5.0' 	# for network communication
  pod 'SwiftyJSON', '~> 3.1'	# For Json stuff
  pod 'Bolts-Swift', '~> 1.3'	# For "promises" programming in Swift

  target 'assignmentTests' do
    inherit! :search_paths
  end

end
